name: E2E Testing
on: push

jobs:
  jest-puppeteer:
    name: Jest Puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Running tests
        run: npm run e2e
